### ISSUE TITLE
KGE with intercept

### ISSUE THREAD

**Issue by nikolauska** [osasto-kuikka/KGE#17]
#### Explanation

[Intercept](https://github.com/NouberNou/intercept) is c++ wrapper to sqf commands to allow much better performance and multi threading. This will require full rewrite of the mod and some of the script we use on kuikka repository should also be redone and implement in as part of KGE.

Some of these might not be implemented for intercept if there is no noticeable improvement, but everything that can be replaced have been added here.
##### Notice

KAC is needed before EDEN update due to update breaking DAC functionality!
#### TODO
- [ ] align
- [ ] autorun
- [ ] common
- [ ] gear
- [ ] loadout
- [ ] respawn
- [ ] spectrator
- [ ] tank recoil
- [ ] teamroster
- [ ] teleport
- [ ] zeus
- [ ] kac (kuikka ai creator, successor to dac)
- [ ] ai (successor to asr ai)
- [ ] hud (replacement to sthud)

**Comment by nikolauska** [comment]
not needed
